JoinCODED/Bootcamps

- README.md
Hey guys. I added this thing.
It closes #9
> Added Spring2018

- README.md
Thanks @DarthHamza for adding my name
> Added Aziz's name to the instructor list

- README.md
> Hamza added his name. Good job.

- README.md
> Added my details to students list

- README.md
> reham edited

- README.md
> Dana's Info

- README.md
> teeny tiny cleanup

- README.md
> trying to fix last task

- README.md
> Added instructors

- README.md
> abdullah alrayes

- README.md
> Added Aldelaigan

- README.md
> added_name

- README.md
Hello everyone I have added an instructor list.
Please check it @Lailz
> Added instructor list

- README.md
* Student list
@Lailz  Please merge me
> Add student list

- README.md
Add myself (Khalid as a student)
> add Khalid as a student

- README.md
> Added Samy to Students

- README.md
Added a new section for Tuwaiq 2019.
@khm56 please review
> New Bootcamp! Tuwaiq 2019!

- README.md
@Pre1 please check for mistakes. There is definitely a mistake.
> Add instructors and students lists

- README.md
> Huss bootcamp

- README.md
> Added my name ;P

- README.md
> MG Add a name

- README.md
> added laila

- README.md
> Added myself: Mshary

- README.md
> Lailz and Hamza

- README.md
added my name to the list of students
> added rashed's name

- README.md
> yousef is first

- README.md
> add Nour Alkandari

- README.md
> Aziz adds his name to the list

- README.md
> Add instructors for SU19

- README.md
> remove duplicates

- README.md
I did the thing @HUSSinBOOTS 
Please merge.
> FGSU19 section

- README.md
@HUSSinBOOTS @khm56 
I did the thing!
> make lists

- README.md
> add aziz and khalid to isntructor list

- README.md
> add Yousef H.

- README.md
> added Hussain h

- README.md
> Amnah Added

- README.md
> Add Mohammad to list of students

- README.md
Added my name in the students list
> Alyaa AlOstad

- README.md
> added samira name

- README.md
Hey @TheMshary I did the thing!
> Add FSFA19

- README.md
> Add instructor and student lists

- README.md
> Aded my name

- README.md
> Added email

- README.md
I added myself as an instructor.
> Add Mshary to the list of instructors

- README.md
> added el maw Hani Hamshari

- README.md
> final commit 2.7

- README.md
Added a new cohort  for Riyadh 2020
> Add cohort

- README.md
> Instructor and student lists

- README.md
Added myself, Hamza, Laila and Khalid
> Add instructors

- README.md
> add ali to students

- README.md
> added Mohammed

- README.md
> add-shahd-name-

- README.md
> hayder is added

- README.md
> hayder updated

- README.md
Reverts JoinCODED/Bootcamps#410
> Revert "added ali"

- README.md
> added Khaled To FS21

- README.md
> Nawaf is testinggg
